require 'rubygems'
require 'test/unit'
gem 'rails', '3.1.1'
require 'active_support'
require 'active_support/test_case'
require 'active_record'
require 'mass_assignment'
require 'models'
require 'mocha'
